services:
  dst-server:
     image: jamesits/dst-server:latest
     deploy:
         restart_policy:
             condition: on-failure
     ports:
        - "10999-11000:10999-11000/udp"
        - "12346-12347:12346-12347/udp"
     volumes:
        - ~/.klei/DoNotStarveTogether:/data
     stop_grace_period: 6m
